package gui;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;

class AddAttribute extends JDialog {

	/**
	 * Creates new form AddAttribute
	 */
	public AddAttribute(Manager manager) {
		this.manager = manager;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
		jLabel1 = new javax.swing.JLabel();
		attributeTypeComboBox = new javax.swing.JComboBox();
		addButton = new javax.swing.JButton();
		attributeNameTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Add Attribute");

		jLabel1.setText("Attribute Type");

		attributeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Public", "Private", "Protected", "Package" }));

		addButton.setText("Add");

		// Call addAttribute method in the manager
		addButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				manager.addAttribute();
			}
		});

		attributeNameTextField
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						attributeNameTextFieldActionPerformed(evt);
					}
				});

		jLabel2.setText("Attribute Name");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(52, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		addButton)
																.addContainerGap())
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						attributeNameTextField)
																				.addComponent(
																						attributeTypeComboBox,
																						0,
																						109,
																						Short.MAX_VALUE))
																.addGap(72, 72,
																		72)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(33, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														attributeNameTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														attributeTypeComboBox,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addGap(16, 16, 16).addComponent(addButton)
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void attributeNameTextFieldActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton addButton;
	private javax.swing.JComboBox attributeTypeComboBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField attributeNameTextField;
	private Manager manager;

	// End of variables declaration
	public javax.swing.JComboBox getAttributeTypeComboBox() {
		return attributeTypeComboBox;
	}

	public void setAttributeTypeComboBox(
			javax.swing.JComboBox attributeTypeComboBox) {
		this.attributeTypeComboBox = attributeTypeComboBox;
	}

	public javax.swing.JTextField getAttributeNameTextField() {
		return attributeNameTextField;
	}

	public void setAttributeNameTextField(
			javax.swing.JTextField attributeNameTextField) {
		this.attributeNameTextField = attributeNameTextField;
	}
}
